### PR TITLE
Get Access Token

### PR DESCRIPTION
**Pull request by Timtech4u**
Implemented API Access Token Request

### CODE REVIEW

**Comment by Timtech4u** [comment]
Hello @tuxpiper , does this looks like a common error:

Screenshot from 2019-06-02 13-50-42

**Comment by tuxpiper** [comment]
@Timtech4u  It looks like CloudFront is configured not to accept the request ... but I can't really say the reason for that. I am guessing you are not using CloudFront directly but heroku?

**Review by tuxpiper — APPROVED** [review]
Looking good :+1: !

**Comment by Timtech4u** [comment]
> Looking good +1 !

Thanks, I'd look into the issue here #2

**Pull request merged**
